### ISSUE TITLE
centOS 7.5运行问题

### ISSUE THREAD

**Issue by plumekanade** [SLiGe/mirai-robot#1]
直接启动会报错要求更换协议，因为不是Windows导致无法滑块，然后根据提示添加了启动参数 `-Dmirai.slider.captcha.supported` 来手动滑块验证，出现报错：
![image](https://user-images.githubusercontent.com/52099872/115057600-d7969900-9f16-11eb-82c9-f4f5f7213fb6.png)
然后输入ticket也没反应
大佬有试过在linux运行么

**Comment by SLiGe** [comment]
最新代码已添加登录解决器, 官方给出的解决办法是,先在本地(常用登录地址)获取到设备信息文件`deviceInfo-{qq}.json`,然后放到服务器上,应该就可以了,目前添加了启动参数robot.protocol, 启动时追加-Drobot.protocol={0} 即可控制使用协议,参考README
