### ISSUE TITLE
, code=235, title=温馨提示, message=当前版本过低，请升级到QQ最新版本。, errorInfo= )

### ISSUE THREAD

**Issue by madGodFucker** [SLiGe/mirai-robot#6]
提示qq版本过低 怎么解决啊

**Comment by SLiGe** [comment]
选择的是Android协议吗？

**Comment by madGodFucker** [comment]
> 
BotConfiguration.MiraiProtocol.ANDROID_PHONE  选的安卓手机

**Comment by SLiGe** [comment]
> > 
> 
> BotConfiguration.MiraiProtocol.ANDROID_PHONE 选的安卓手机

QQ账号是不是等级低，并且不是常用登录环境，可以先挂几天QQ再试试

**Comment by madGodFucker** [comment]
qq账号是等级低，那再挂几天
